### ISSUE TITLE
post install script errors on npm install or gulp clean

### ISSUE THREAD

**Issue by Jeff-Weiss-WAWD-USCOURTS-gov** [Voitanos/eslint-preset-spfx-react#1]
I installed the preset eslint-preset-spfx-react. If I delete node_modules and run npm install, or if I run gulp clean, the postinstall.js throws an error when it doesn't find tslint.json, and the gulpfile.js gets extended with the delta again causing  duplicate variable declaration errors.

**Comment by andrewconnell** [comment]
fixed in v1.2
